//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_satislar
    {
        public int satis_id { get; set; }
        public Nullable<int> urun { get; set; }
        public Nullable<int> musteri { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<decimal> fiyat { get; set; }
    
        public virtual tbl_musteri tbl_musteri { get; set; }
        public virtual tbl_urunler tbl_urunler { get; set; }
    }
}
